{% set name = "biorbd" %}
{% set version = "1.9.3" %}
{% set build_num = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/{{ name }}/archive/Release_{{ version }}.tar.gz
  sha256: 7580e21b1cd3c0f18483b735846d2a9726ff0a3953a6cebe6c06b6976e609525

build:
  number: {{ build_num }}
  rpaths:
    - lib/
    - lib/{{ name }}/
  run_exports:
    - {{ pin_subpackage('biorbd', max_pin='x.x') }}
  skip: true  # [py<310]
requirements:
  build:
    - cmake
    - ninja
    - pkgconfig
    - {{ compiler('cxx') }}
  host:
    - rbdl >=3.1.3
    - ipopt
    - tinyxml
    - numpy
    - python
    - swig
    - scipy
  run:
    - {{ pin_compatible('rbdl') }}
    - tinyxml
    - ipopt
    - python
    - scipy
    - {{ pin_compatible('numpy') }}

test:
  commands:
    - test -f $PREFIX/lib/biorbd_casadi/libbiorbd_casadi$SHLIB_EXT  # [unix]
    - test -f $PREFIX/lib/biorbd_eigen/libbiorbd_eigen$SHLIB_EXT  # [unix]
    - if not exist %LIBRARY_PREFIX%\\Lib\\biorbd_casadi*.lib exit 1  # [win]
    - if not exist %LIBRARY_PREFIX%\\Lib\\biorbd_eigen*.lib exit 1  # [win]
  imports:
    - biorbd
    - biorbd_casadi

about:
  home: http://github.com/pyomeca/biorbd
  license: MIT
  license_file: LICENSE
  summary: 'Biomechanical add-ons to the RigidBody Dynamics Library '

  description: |
    Biomechanical add-ons to the RigidBody Dynamics Library .
  doc_url: https://github.com/pyomeca/biorbd/
  dev_url: https://github.com/pyomeca/biorbd/

extra:
  recipe-maintainers:
    - pariterre
