{% set name = "biorbd" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/{{ name }}/archive/Release_{{ version }}.tar.gz
  sha256: 5c5e4070c250ce74b53f45f9f3235bbeb6a264405723b7ba6b546799631bb106
  
build:
  number: 0
  skip: True  # [win and vc<14]
  skip: True  # [py<35]
  rpaths:
    - lib/
    - lib/{{ name }}/

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - libblas
    - libcblas
    - boost-cpp
    - eigen
    - rbdl
    - dlib-cpp
    - python
    - numpy
    - swig
  run:
    - boost-cpp
    - eigen
    - rbdl
    - dlib-cpp
    - python
    - numpy

test: 
  commands: 
    - test -f $PREFIX/lib/biorbd/libbiorbd$SHLIB_EXT  # [unix] 
    - if not exist %PREFIX%\\Lib\\biorbd*.lib exit 1  # [win]
  imports:
    - biorbd

about:
  home: http://github.com/pyomeca/biorbd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Biomechanical add-ons to the RigidBody Dynamics Library '

  description: |
    Biomechanical add-ons to the RigidBody Dynamics Library .
  doc_url: https://github.com/pyomeca/biorbd/
  dev_url: https://github.com/pyomeca/biorbd/

extra:
  recipe-maintainers:
    - pariterre
