{% set name = "biorbd" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/{{ name }}/archive/Release_{{ version }}.tar.gz
  sha256: 76b62f918a29d383ca28b8816e6ff15d30bfd0808a55a08174bb7d054e43b737

build:
  number: 1
  skip: True  # [win and vc<14]
  skip: True  # [py<35]
  rpaths:
    - lib/
    - lib/{{ name }}/

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - libblas
    - libcblas
    - boost-cpp
    - eigen
    - rbdl
    - dlib-cpp
    - tinyxml
    - python
    - numpy
    - swig
  run:
    - boost-cpp
    - eigen
    - rbdl
    - dlib-cpp
    - python
    - numpy

test:
  commands:
    - test -f $PREFIX/lib/biorbd/libbiorbd$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Lib\\biorbd*.lib exit 1  # [win]
  imports:
    - biorbd

about:
  home: http://github.com/pyomeca/biorbd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Biomechanical add-ons to the RigidBody Dynamics Library '

  description: |
    Biomechanical add-ons to the RigidBody Dynamics Library .
  doc_url: https://github.com/pyomeca/biorbd/
  dev_url: https://github.com/pyomeca/biorbd/

extra:
  recipe-maintainers:
    - pariterre
