{% set name = "biorbd" %}
{% set version = "1.8.3" %}
{% set build_num = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pariterre/{{ name }}/archive/Release_{{ version }}.tar.gz
  sha256: cdd4264d5ad73088a7ff820f8e749254497565cf7324922b4ddabef5be6b63be

build:
  number: {{ build_num }}
  rpaths:
    - lib/
    - lib/{{ name }}/
  run_exports:
    - {{ pin_subpackage('biorbd', max_pin='x.x') }}
  string: py{{ py }}_h{{ PKG_HASH }}_{{ build_num }}
requirements:
  build:
    - cmake
    - pkgconfig
    - ninja
    - {{ compiler('cxx') }}
  host:
    - rbdl >=3.1.3
    - ipopt
    - tinyxml
    - numpy >=1.19
    - swig
  run:
    - {{ pin_compatible('rbdl') }}
    - tinyxml
    - ipopt
    - {{ pin_compatible('numpy') }}

test:
  commands:
    - test -f $PREFIX/lib/biorbd_casadi/libbiorbd_casadi$SHLIB_EXT  # [unix]
    - test -f $PREFIX/lib/biorbd_eigen/libbiorbd_eigen$SHLIB_EXT  # [unix]
    - if not exist %PREFIX%\\Lib\\biorbd_casadi*.lib exit 1  # [win]
    - if not exist %PREFIX%\\Lib\\biorbd_eigen*.lib exit 1  # [win]
  imports:
    - biorbd
    - biorbd_casadi

about:
  home: http://github.com/pyomeca/biorbd
  license: MIT
  license_file: LICENSE
  summary: 'Biomechanical add-ons to the RigidBody Dynamics Library '

  description: |
    Biomechanical add-ons to the RigidBody Dynamics Library .
  doc_url: https://github.com/pyomeca/biorbd/
  dev_url: https://github.com/pyomeca/biorbd/

extra:
  recipe-maintainers:
    - pariterre
